name: Build IP Switcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: x86_64
            python-arch: x64
          - os: macos-14
            arch: arm64
            python-arch: arm64
          - os: windows-latest
            arch: x86_64
            python-arch: x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: ${{ matrix.python-arch }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Generate icons
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          # Generate ICO file for Windows (using ImageMagick if available, otherwise skip)
          if command -v magick &> /dev/null; then
            magick convert icon.png -resize 256x256 ip_switcher.ico
          elif command -v convert &> /dev/null; then
            convert icon.png -define icon:auto-resize=256,128,64,32,16 ip_switcher.ico
          else
            echo "ImageMagick not available, skipping icon generation"
          fi
        else
          # Generate ICNS file for macOS
          make icons
        fi
      shell: bash
      continue-on-error: true

    - name: Build with Nuitka
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          # Build for Windows - simplified flags to avoid path issues
          if [ -f "ip_switcher.ico" ]; then
            python -m nuitka --onefile --windows-disable-console --enable-plugin=tk-inter --include-package=tkinter --include-package=_tkinter --assume-yes-for-downloads --windows-icon-from-ico=ip_switcher.ico --output-filename=ip_switcher.exe ip_switcher.py
          else
            python -m nuitka --onefile --windows-disable-console --enable-plugin=tk-inter --include-package=tkinter --include-package=_tkinter --assume-yes-for-downloads --output-filename=ip_switcher.exe ip_switcher.py
          fi
        else
          # Build for macOS - create .app bundle, disable codesigning
          export NUITKA_MACOS_CODESIGN=no
          if [ -f "ip_switcher.icns" ]; then
            python -m nuitka --onefile --enable-plugin=tk-inter --include-package=tkinter --include-package=_tkinter --assume-yes-for-downloads --nofollow-import-to=unittest --nofollow-import-to=test --include-module=_bisect --include-module=_json --macos-create-app-bundle --macos-app-icon=ip_switcher.icns --macos-app-name="IP Switcher" --macos-app-version="1.0" ip_switcher.py
          else
            python -m nuitka --onefile --enable-plugin=tk-inter --include-package=tkinter --include-package=_tkinter --assume-yes-for-downloads --nofollow-import-to=unittest --nofollow-import-to=test --include-module=_bisect --include-module=_json --macos-create-app-bundle --macos-app-name="IP Switcher" --macos-app-version="1.0" ip_switcher.py
          fi
          # Clean extended attributes from .app bundle
          find ip_switcher.app -type f -exec xattr -c {} \; 2>/dev/null || true
          find ip_switcher.app -name "._*" -delete 2>/dev/null || true
          find ip_switcher.app -name ".DS_Store" -delete 2>/dev/null || true
          # Add Info.plist and icon to app bundle
          mkdir -p ip_switcher.app/Contents/Resources
          cp Info.plist ip_switcher.app/Contents/ 2>/dev/null || true
          if [ -f "ip_switcher.icns" ]; then
            cp ip_switcher.icns ip_switcher.app/Contents/Resources/ 2>/dev/null || true
          fi
        fi
      shell: bash

    - name: Prepare artifacts for Windows
      if: matrix.os == 'windows-latest'
      run: |
        if [ -f "ip_switcher.exe" ]; then
          mv ip_switcher.exe ip_switcher-windows-${{ matrix.arch }}.exe
        else
          echo "Warning: ip_switcher.exe not found"
        fi
      shell: bash

    - name: Prepare artifacts for macOS
      if: startsWith(matrix.os, 'macos')
      run: |
        # For macOS, we get a .app bundle, compress it
        if [ -d "ip_switcher.app" ]; then
          tar -czf ip_switcher-macos-${{ matrix.arch }}.tar.gz ip_switcher.app
        else
          echo "Warning: ip_switcher.app not found"
        fi
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ip_switcher-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          ip_switcher-windows-*.exe
          ip_switcher-macos-*.tar.gz
        compression-level: 9
        retention-days: 5
        if-no-files-found: warn

    - name: Upload release assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ip_switcher-windows-*.exe
          ip_switcher-macos-*.tar.gz
        fail_on_unmatched_files: false